package LeetCodeJava.BitManipulation;

// https://leetcode.com/problems/find-the-difference/

/**
 *  389. Find the Difference
 *  Easy
 *
 *  You are given two strings s and t.
 *
 *  String t is generated by random shuffling string s and then add one more
 *  letter at a random position.
 *
 *  Return the letter that was added to t.
 *
 *  Example 1:
 *
 *  Input: s = "abcd", t = "abcde"
 *  Output: "e"
 *  Explanation: 'e' is the letter that was added.
 *
 *  Example 2:
 *
 *  Input: s = "", t = "y"
 *  Output: "y"
 *
 *  Constraints:
 *
 *  0 <= s.length <= 1000
 *  t.length == s.length + 1
 *  s and t consist of lowercase English letters.
 */
public class FindTheDifference {

    // V0
    // IDEA: XOR everything, the pairs cancel out and only the extra char remains
    /**
     * time = O(n)
     * space = O(1)
     */
    public char findTheDifference(String s, String t) {
        char res = 0;
        for (int i = 0; i < s.length(); i++) {
            res ^= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            res ^= t.charAt(i);
        }
        return res;
    }

    // V1
    // IDEA: sum of char codes, difference is the added letter
    /**
     * time = O(n)
     * space = O(1)
     */
    public char findTheDifference_1(String s, String t) {
        int sum = 0;
        for (int i = 0; i < s.length(); i++) {
            sum -= s.charAt(i);
        }
        for (int i = 0; i < t.length(); i++) {
            sum += t.charAt(i);
        }
        return (char) sum;
    }
}
