package AlgorithmJava;

import java.util.*;

/**
 *  TopologicalSort V1
 *
 */
public class TopologicalSort {

    // V1
    // (generated by GPT)
    /**
     *  TopologicalSort STEP
     *
     *   (BFS)
     *
     *   Step 1) build graph, (and topoOrder, index)
     *   Step 2) find degree = 0 node, put into queue
     *   Step 3) pop node from queue, find its neighbor, make degree -= 1,
     *           if degree = 0 node, put into queue
     *   Step 4) repeat  Step 1) -  Step 3)
     *
     *
     */
    /**
     *
     * Kahn's Algorithm for Topological Sort (with BFS)
     *
     * 1) Identify nodes with no incoming edges and add them to the queue.
     *
     * 2) While the queue is not empty:
     *     - Remove a node from the queue and add it to the topological order.
     *     - For each outgoing edge from that node, reduce the in-degree of the target node by 1.
     *     - If the in-degree of the target node becomes 0, add it to the queue.
     *
     * 3) If the number of nodes added to the topological order is less
     *    than the total number of nodes, the graph has at least one cycle,
     *    and a topological sort is not possible.
     *
     */
    public int[] topologicalSort(int numCourses, int[][] prerequisites) {

        /**  NOTE !!!
         *
         *   we create 2 things for topological sort
         *
         *   1) List<List<Integer>> graph : for tracking nodes and their "prerequisite" node
         *
         *   2) int[] inDegree = new int[numCourses] : for tracking "degree" of a node,
         *                                             when degree==0, the node CAN be ACCESSED
         *
         */

        // Step 1: Build the graph
        List<List<Integer>> graph = new ArrayList<>();
        for (int i = 0; i < numCourses; i++) {
            graph.add(new ArrayList<>());
        }

        int[] inDegree = new int[numCourses];
        for (int[] prereq : prerequisites) {

            /**
             *  NOTE !!!
             *
             *   given prereq = [dest, src]
             *
             *   -> the dependency ordering:
             *
             *      src first, then dest
             *
             *
             *   Example :
             *
             *    int[][] prerequisites = { {1, 0}, {2, 0}, {3, 1}, {3, 2} };
             *
             *    -> 0 is the prerequisite for 1 and 2.
             *    -> 1 and 2 are the prerequisites for 3.
             *
             */
            // int dest = prereq[0];: dest represents the course that depends on src.
            int dest = prereq[0];
            // int src = prereq[1];: src represents the course that is a prerequisite.
            int src = prereq[1];
            graph.get(src).add(dest);
            /**
             *  Example:
             *
             *
             *  For the pair {1, 0}:
             *
             * 	- src = 0, dest = 1
             * 	- graph.get(0).add(1) adds 1 to the adjacency list of 0.
             * 	- inDegree[1]++ increments the in-degree of 1 by 1.
             *
             *
             *  For the pair {2, 0}:
             *
             * 	- src = 0, dest = 2
             * 	- graph.get(0).add(2) adds 2 to the adjacency list of 0.
             * 	- inDegree[2]++ increments the in-degree of 2 by 1.
             *
             *
             * 	 For the pair {3, 1}:
             *
             * 	- src = 1, dest = 3
             * 	- graph.get(1).add(3) adds 3 to the adjacency list of 1.
             * 	- inDegree[3]++ increments the in-degree of 3 by 1.
             *
             */
            inDegree[dest]++; // update the "dependency count" of dest node
        }

        // Step 2: Initialize the queue with nodes having in-degree of 0
        Queue<Integer> queue = new LinkedList<>();
        for (int i = 0; i < numCourses; i++) {
            // NOTE !!! ONLY put node into queue when its "degree" == 0
            if (inDegree[i] == 0) {
                queue.add(i);
            }
        }

        // Step 3: Perform Kahn's algorithm
        /**
         *
         *
         * "topoOrder" is an array that will hold the nodes in their topologically sorted order.
         *
         * "index" keeps track of the current position in this array where the next node should be placed.
         *
         *
         */
        int[] topoOrder = new int[numCourses];
        int index = 0;

        while (!queue.isEmpty()) {
            /**
             * NOTE !!!
             *
             *  since only  "degree" == 0 node was put into queue,
             *  so here, all pop node are with "degree" == 0
             *  so they are already visited, and it's OK to add them to the result array (topoOrder)
             */
            int node = queue.poll();
            topoOrder[index++] = node;

            // Reduce the in-degree of adjacent nodes by 1
            /**
             *  NOTE !!!
             *
             *   visit node's neighbor,
             *   make it degree -= 1
             *   and if degree == 0, put such node (neighbor) to queue
             */
            for (int neighbor : graph.get(node)) {
                inDegree[neighbor]--;
                if (inDegree[neighbor] == 0) {
                    queue.add(neighbor);
                }
            }
        }

        // Check if a valid topological order is possible
        // NOTE !!!  if index != numCourses -> graph has a cycle, so it's NOT possible to perform topological sort on it
        if (index != numCourses) {
            return new int[0]; // Return an empty array if the graph has a cycle
        }

        return topoOrder;
    }

    // V2
    // Union Find (for connected components, e.g. LC 547 Number of Provinces)
    /**
     *  Union Find STEP
     *
     *   Step 1) Initialize: each node is its own parent, cluster count = n
     *   Step 2) For each edge (connection), union the two nodes
     *   Step 3) Union: find roots of both nodes via path compression,
     *           if different roots, merge and decrement cluster count
     *   Step 4) Result: cluster count = number of connected components
     *
     *  Difference from Topological Sort:
     *   - Works on UNDIRECTED graphs (not DAGs)
     *   - Finds connected components (not linear ordering)
     *   - Uses parent array + path compression (not in-degree + queue)
     */
    /**
     * time = O(N^2 * α(N)) where α is inverse Ackermann function (nearly O(1))
     * space = O(N)
     */
    public int findConnectedComponents(int[][] isConnected) {
        int n = isConnected.length;
        int[] parent = new int[n];
        int[] rank = new int[n];
        int count = n;

        // Step 1: Initialize - each node is its own parent
        for (int i = 0; i < n; i++) {
            parent[i] = i;
        }

        // Step 2: Union connected nodes
        for (int i = 0; i < n; i++) {
            for (int j = i + 1; j < n; j++) {
                if (isConnected[i][j] == 1) {
                    int rootI = find(parent, i);
                    int rootJ = find(parent, j);
                    if (rootI != rootJ) {
                        // Union by rank
                        if (rank[rootI] < rank[rootJ]) {
                            parent[rootI] = rootJ;
                        } else if (rank[rootI] > rank[rootJ]) {
                            parent[rootJ] = rootI;
                        } else {
                            parent[rootJ] = rootI;
                            rank[rootI]++;
                        }
                        count--;
                    }
                }
            }
        }

        return count;
    }

    /** Find with path compression */
    private int find(int[] parent, int x) {
        if (parent[x] != x) {
            parent[x] = find(parent, parent[x]);
        }
        return parent[x];
    }

    // test
    public static void main(String[] args) {

        TopologicalSort topoSort = new TopologicalSort();
        int numCourses = 4;
        // Directed Acyclic Graph (DAG) where each directed edge u -> v means that u comes before v.
        //int[][] prerequisites = {{1, 0}, {2, 0}, {3, 1}, {3, 2}};
        int[][] prerequisites = {{1, 0}, {3, 1}, {2, 0}, {3, 2}};

        int[] result = topoSort.topologicalSort(numCourses, prerequisites);
        System.out.println("Topological Order: " + Arrays.toString(result));

        // Test Union Find (LC 547 Number of Provinces)
        int[][] isConnected1 = {{1,1,0},{1,1,0},{0,0,1}};
        System.out.println("Provinces (expect 2): " + topoSort.findConnectedComponents(isConnected1));

        int[][] isConnected2 = {{1,0,0},{0,1,0},{0,0,1}};
        System.out.println("Provinces (expect 3): " + topoSort.findConnectedComponents(isConnected2));
    }

}
