"""

1332. Remove Palindromic Subsequences
Easy

You are given a string s consisting only of letters 'a' and 'b'.
In a single step you can remove one palindromic subsequence from s.

Return the minimum number of steps to make the given string empty.

A string is a subsequence of a given string if it is generated by deleting
some characters of a given string without changing its order.
Note that a subsequence does not necessarily need to be contiguous.

A string is called palindrome if is one that reads the same backward
as well as forward.


Example 1:

Input: s = "ababa"
Output: 1
Explanation: s is already a palindrome, so its entirety can be removed in a single step.

Example 2:

Input: s = "abb"
Output: 2
Explanation: "abb" -> "bb" -> "".
Remove palindromic subsequence "a" then "bb".

Example 3:

Input: s = "baabb"
Output: 2
Explanation: "baabb" -> "b" -> "".
Remove palindromic subsequence "baab" then "b".


Constraints:

1 <= s.length <= 1000
s[i] is either 'a' or 'b'.

"""

# V0
# IDEA: STRING + MATH
#
#  - s only has 'a' and 'b'.
#  - all 'a' form a palindromic subsequence ("aaa...a"),
#    likewise all 'b'. So the answer is NEVER more than 2.
#  - if s is empty -> 0 step
#  - if s is already a palindrome -> 1 step (remove the whole string)
#  - otherwise -> 2 steps (remove all 'a', then all 'b')
#
# time = O(n)
# space = O(n)
class Solution(object):
    def removePalindromeSub(self, s):
        # edge
        if not s:
            return 0
        return 1 if s == s[::-1] else 2


# V0-1
# IDEA: TWO POINTERS (O(1) space palindrome check)
# time = O(n)
# space = O(1)
class Solution(object):
    def removePalindromeSub(self, s):
        if not s:
            return 0
        i, j = 0, len(s) - 1
        while i < j:
            if s[i] != s[j]:
                return 2
            i += 1
            j -= 1
        return 1
