#!/usr/bin/env python3
"""
The L3 core set — the ~100 problems this repo measures itself on — and where
each one stands in the practice log.

    python3 script/l3_core.py                     # status: every problem, its latest verdict
    python3 script/l3_core.py status --only again # just the ones still coming back
    python3 script/l3_core.py next 5              # the session: five problems to drill
    python3 script/l3_core.py refresh             # (re)write data/l3_core.json
    python3 script/l3_core.py refresh --check     # exit 1 if that file is stale
    python3 script/l3_core.py status --json out.json   # the numbers, for monthly tracking

Why a fixed set. The Aug 2026 readiness run scored Volume and Breadth at A for
the Google L3 bar and said more solved problems cannot move the grade; the Sep
2026 project review (doc/project-review-2026-09.md) found the loop that is not
closing is *solved → solid*: Blind 75's latest log verdict was `ok` for 14 of 75.
A percentage only means something on a set that does not move, so the set is
pinned here and every number below is computed against it.

The rule: Blind 75, plus the NeetCode 150 problems README marks `MUST`. Blind 75
is what every interviewer has seen; the MUST marker is the owner's own must-know
verdict, so the second half adds the NeetCode problems *this* preparation has
already decided matter (Dijkstra, topological sort, the interval family …)
without the rest of the 150. 98 problems at the time of writing. README's
`google` tag was tried first and rejected: it marks 37% of the index, so
NeetCode 150 ∩ google is 147 — NeetCode 150 with three problems missing.

Where the numbers come from. `data/progress.txt` is the primary record — it is
written daily, README's status column is not — so the verdict this script
reports is *the latest annotation the log gives a problem*: `ok`, `again`, or
none (a bare number or a `todo`). README's `OK`/`AGAIN` is shown beside it as
the slower-moving view, never instead of it. Parsing is shared with
script/suggest_review.py so the two planners cannot disagree about a line.

What it never does: write the log or README. A session picked here is logged
with /lc-log and promoted with /lc-again, which own those files.
"""
import argparse
import json
import os
import re
import sys
import time
from collections import Counter, OrderedDict, defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import suggest_review as sr  # noqa: E402  — one README parser, one log parser

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
README = os.path.join(REPO, "README.md")
PROGRESS = os.path.join(REPO, "data", "progress.txt")
LISTS = os.path.join(REPO, "data", "problem_lists.json")
OUT = os.path.join(REPO, "data", "l3_core.json")

RULE = "blind75 | (neetcode150 & readme:must)"

# An `ok` older than this is a candidate again: the review plan's own intervals
# put a fourth clean pass at roughly a month, and the point of the set is that
# nothing on it is allowed to quietly rot.
OK_STALE_DAYS = 30
# A problem logged this recently is not offered again — today's session should
# not be tomorrow's session.
RECENT_DAYS = 3
# Latest verdict `again` after this many attempts is what the review called a
# chronic problem, and what the derivation cards are written for.
CHRONIC_ATTEMPTS = 8

DAY = 86400.0


# ── The set ─────────────────────────────────────────────────────────────────
def core_ids(problems, lists):
    """The rule, as a sorted list of LC ids.

    `problems` is parse_readme's map; `lists` is load_problem_lists' map. Only
    problems README indexes are eligible — the readiness of a problem with no
    row and no solution here is not this repo's to report.
    """
    ids = set()
    for lc, names in lists.items():
        if lc not in problems:
            continue
        if "blind75" in names:
            ids.add(lc)
        elif "neetcode150" in names and problems[lc]["must"]:
            ids.add(lc)
    return sorted(ids)


def load_core(path=OUT):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def write_core(ids, path=OUT):
    payload = OrderedDict([
        ("_comment",
         "Generated by `python3 script/l3_core.py refresh` — do not edit by hand. "
         "The L3 core set: " + RULE + ". Read by site/build-roadmap.js (the roadmap's "
         "`l3-core` list, `from: file:l3_core`) and by the /l3-core skill; only the ids "
         "live here, titles and difficulty come from README at build time."),
        ("rule", RULE),
        ("count", len(ids)),
        ("ids", ids),
    ])
    text = json.dumps(payload, indent=2) + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(text)
    return text


# ── The log ─────────────────────────────────────────────────────────────────
def _verdict(note):
    """`again` beats `ok` when a note says both — "(ok, but again)" still needs
    a pass. Anything else — todo, a bare number, a free note — is no verdict."""
    word = sr._classify(note)
    return word if word in ("again", "ok") else "none"


def latest_verdicts(path=PROGRESS):
    """-> {lc: {"verdict", "ts", "attempts", "first_ts"}}, warnings.

    Walks the log the way suggest_review.parse_progress does (same date rule,
    same label stripping, same top-level split) but keeps *which* annotation
    was the latest rather than a Counter of all of them. Within one day the
    later entry wins, so "139(again), ... 139(ok)" on a single line reads ok.
    """
    if not os.path.exists(path):
        return {}, ["%s not found" % path]
    state = {}
    warnings = []
    current_ts = None
    pending = None

    def depth_of(text):
        depth = 0
        for ch in text:
            if ch == "(":
                depth += 1
            elif ch == ")":
                depth = max(0, depth - 1)
        return depth

    def flush():
        if pending is None or current_ts is None:
            return
        for chunk in sr._split_top_level(pending.replace("|", ",")):
            entry = chunk.strip()
            if not entry:
                continue
            m = re.match(r"^(\d+)\s*(?:\((.*)\))?", sr._strip_label(entry))
            if not m:
                continue
            lc = int(m.group(1))
            rec = state.setdefault(lc, {"verdict": "none", "ts": None, "attempts": 0, "first_ts": None})
            rec["attempts"] += 1
            if rec["first_ts"] is None or current_ts < rec["first_ts"]:
                rec["first_ts"] = current_ts
            if rec["ts"] is None or current_ts >= rec["ts"]:
                rec["ts"] = current_ts
                rec["verdict"] = _verdict(m.group(2))

    with open(path, encoding="utf-8") as f:
        lines = f.read().split("\n")

    for i, raw in enumerate(lines):
        trimmed = raw.strip()
        mid_annotation = pending is not None and depth_of(pending) > 0
        if not trimmed or re.match(r"^[-=]{2,}", trimmed):
            flush()
            pending = None
            continue
        header = re.match(r"^(\d{8})\s*[:.]?\s*(.*)$", trimmed)
        if header:
            flush()
            try:
                current_ts = time.mktime(time.strptime(header.group(1), "%Y%m%d"))
            except ValueError:
                warnings.append("line %d: unreadable date %r" % (i + 1, header.group(1)))
                current_ts = None
            pending = header.group(2)
            continue
        if pending is None:
            if current_ts is None:
                continue
            pending = trimmed
        else:
            pending += ("" if mid_annotation else ",") + trimmed
    flush()
    return state, warnings


# ── Rows ────────────────────────────────────────────────────────────────────
def build_rows(ids, problems, log, now=None):
    now = time.time() if now is None else now
    rows = []
    for lc in ids:
        p = problems[lc]
        rec = log.get(lc)
        if rec is None:
            verdict, days, attempts = "never", None, 0
        else:
            verdict = rec["verdict"]
            days = int((now - rec["ts"]) // DAY) if rec["ts"] is not None else None
            attempts = rec["attempts"]
        rows.append({
            "lc": lc,
            "title": p["title"],
            "section": p["section"],
            "difficulty": p["difficulty"] or "?",
            "verdict": verdict,           # ok | again | none | never
            "days": days,                 # since the latest log mention
            "attempts": attempts,
            "readme": p["status"] or "",  # OK | AGAIN | TODO | NOT_OK | ''
            "passes": p["passes"],
            "must": p["must"],
        })
    return rows


def summarise(rows):
    c = Counter(r["verdict"] for r in rows)
    size = len(rows)
    by_section = defaultdict(lambda: Counter())
    for r in rows:
        by_section[r["section"]][r["verdict"]] += 1
        by_section[r["section"]]["total"] += 1
    chronic = sorted((r for r in rows if r["verdict"] == "again" and r["attempts"] >= CHRONIC_ATTEMPTS),
                     key=lambda r: -r["attempts"])
    return {
        "size": size,
        "ok": c["ok"], "again": c["again"], "none": c["none"], "never": c["never"],
        "ok_share": round(c["ok"] / size, 3) if size else 0.0,
        "unverdicted": c["none"] + c["never"],
        "chronic": [r["lc"] for r in chronic],
        "by_section": {s: dict(v) for s, v in sorted(by_section.items())},
    }


# ── The session ─────────────────────────────────────────────────────────────
def _priority(row):
    """Lower sorts first. Never attempted, then attempted without a verdict,
    then `again` (oldest first), then a stale `ok`. A fresh `ok` is not
    offered: the set is for closing gaps, not for re-proving what is solid."""
    v, days = row["verdict"], row["days"]
    if v == "never":
        return (0, 0)
    if v == "none":
        return (1, -(days or 0))
    if v == "again":
        return (2, -(days or 0))
    if v == "ok" and days is not None and days >= OK_STALE_DAYS:
        return (3, -days)
    return None


def pick(rows, n, recent_days=RECENT_DAYS):
    """Round-robin across README sections in priority order, like
    suggest_review.pick: a five-problem session should not be five DP rows."""
    eligible = []
    for r in rows:
        if r["days"] is not None and r["days"] < recent_days:
            continue
        pr = _priority(r)
        if pr is None:
            continue
        eligible.append((pr, r))
    eligible.sort(key=lambda t: (t[0], t[1]["lc"]))

    queues = OrderedDict()
    for pr, r in eligible:
        queues.setdefault(r["section"], []).append(r)
    # sections in the order of their best candidate
    order = sorted(queues, key=lambda s: _priority(queues[s][0]))

    out = []
    while len(out) < n and any(queues.values()):
        for s in order:
            if queues[s]:
                out.append(queues[s].pop(0))
                if len(out) == n:
                    break
    return out


def why(row):
    v = row["verdict"]
    if v == "never":
        return "never in the log"
    if v == "none":
        return "attempted %d×, no verdict ever given" % row["attempts"]
    if v == "again":
        return "again, %d× (last %sd ago)" % (row["attempts"], row["days"])
    return "ok but %dd stale" % row["days"]


# ── Output ──────────────────────────────────────────────────────────────────
def fmt_row(r):
    days = "-" if r["days"] is None else "%dd" % r["days"]
    readme = (r["readme"] or "-") + ("*" * min(r["passes"], 3) + ("+" if r["passes"] > 3 else "") if r["passes"] else "")
    return "%5d  %-44s %-20s %-6s %-6s %3d× %5s  %s" % (
        r["lc"], r["title"][:44], r["section"][:20], r["difficulty"][:6],
        r["verdict"], r["attempts"], days, readme)


def render_status(rows, summary, warnings, markdown=False):
    out = []
    if markdown:
        out.append("| # | Title | Section | Diff | Log verdict | Attempts | Last | README |")
        out.append("|---|---|---|---|---|---|---|---|")
        for r in rows:
            days = "-" if r["days"] is None else "%dd" % r["days"]
            out.append("| %d | %s | %s | %s | %s | %d | %s | %s |" % (
                r["lc"], r["title"], r["section"], r["difficulty"], r["verdict"],
                r["attempts"], days, r["readme"] or "-"))
        out.append("")
    else:
        out.append("%5s  %-44s %-20s %-6s %-6s %4s %5s  %s" % (
            "#", "title", "section", "diff", "log", "n", "last", "readme"))
        for r in rows:
            out.append(fmt_row(r))
        out.append("")
    s = summary
    out.append("L3 core: %d problems (%s)" % (s["size"], RULE))
    out.append("  latest log verdict   ok %3d (%.0f%%)   again %3d   no verdict %3d   never logged %3d"
               % (s["ok"], 100 * s["ok_share"], s["again"], s["none"], s["never"]))
    if s["chronic"]:
        out.append("  chronic (again, %d+ attempts): %s" % (
            CHRONIC_ATTEMPTS, ", ".join(str(x) for x in s["chronic"])))
    out.append("  by section:")
    for sec, c in s["by_section"].items():
        out.append("    %-22s %3d   ok %3d  again %3d  none %3d" % (
            sec, c.get("total", 0), c.get("ok", 0), c.get("again", 0),
            c.get("none", 0) + c.get("never", 0)))
    for w in warnings:
        out.append("  warning: " + w)
    return "\n".join(out)


def render_next(picked, markdown=False):
    if not picked:
        return "nothing to drill: every problem on the set is ok and fresh, or was logged in the last %d days" % RECENT_DAYS
    out = []
    if markdown:
        out.append("| # | Title | Section | Diff | Why |")
        out.append("|---|---|---|---|---|")
        for r in picked:
            out.append("| %d | %s | %s | %s | %s |" % (r["lc"], r["title"], r["section"], r["difficulty"], why(r)))
    else:
        for r in picked:
            out.append("%5d  %-44s %-20s %-6s  %s" % (r["lc"], r["title"][:44], r["section"][:20], r["difficulty"][:6], why(r)))
    out.append("")
    out.append("log it afterwards with /lc-log, every problem with a verdict: " +
               ", ".join("%d(ok|again)" % r["lc"] for r in picked))
    return "\n".join(out)


# ── Entry point ─────────────────────────────────────────────────────────────
def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd")

    st = sub.add_parser("status", help="every problem on the set and its latest log verdict (default)")
    st.add_argument("--only", choices=["ok", "again", "none", "never"], help="filter by latest verdict")
    st.add_argument("--section", help="filter by README section (substring, case-insensitive)")
    st.add_argument("--json", metavar="PATH", help="also write the summary as JSON, for monthly tracking")
    st.add_argument("--markdown", action="store_true", help="table as markdown, for pasting")

    nx = sub.add_parser("next", help="pick a session")
    nx.add_argument("n", nargs="?", type=int, default=5)
    nx.add_argument("--exclude-recent", type=int, default=RECENT_DAYS, metavar="DAYS",
                    help="skip problems logged this recently (default %d)" % RECENT_DAYS)
    nx.add_argument("--markdown", action="store_true")

    rf = sub.add_parser("refresh", help="(re)write data/l3_core.json from the rule")
    rf.add_argument("--check", action="store_true", help="exit 1 if the file is stale instead of writing it")

    args = ap.parse_args(argv)
    cmd = args.cmd or "status"

    problems = sr.parse_readme(README)
    lists = sr.load_problem_lists(LISTS)
    ids = core_ids(problems, lists)

    if cmd == "refresh":
        current = load_core()
        stale = current is None or current.get("ids") != ids or current.get("rule") != RULE
        if args.check:
            if stale:
                print("data/l3_core.json is stale — run: python3 script/l3_core.py refresh")
                return 1
            print("data/l3_core.json is up to date (%d problems)" % len(ids))
            return 0
        write_core(ids)
        before = len(current.get("ids", [])) if current else 0
        print("wrote data/l3_core.json: %d problems%s" % (
            len(ids), "" if not stale else " (was %d)" % before if current else " (new file)"))
        return 0

    log, warnings = latest_verdicts()
    rows = build_rows(ids, problems, log)

    if cmd == "next":
        picked = pick(rows, args.n, args.exclude_recent)
        print(render_next(picked, args.markdown))
        return 0

    shown = rows
    if args.only:
        shown = [r for r in shown if r["verdict"] == args.only]
    if args.section:
        shown = [r for r in shown if args.section.lower() in r["section"].lower()]
    summary = summarise(rows)
    print(render_status(shown, summary, warnings, args.markdown))
    if args.json:
        payload = dict(summary, generated=time.strftime("%Y-%m-%d"), rule=RULE)
        with open(args.json, "w", encoding="utf-8") as f:
            json.dump(payload, f, indent=2)
        print("wrote %s" % args.json)
    return 0


if __name__ == "__main__":
    sys.exit(main())
