#!/usr/bin/env python3
"""Regenerate doc/branch-progress.md from real repo state.

The doc is generated, never hand-written: every number below comes from git or from
re-running verify.py over the dispatched files, so it cannot drift from what is on disk.
"""
import json, os, subprocess, sys, datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
BATCHES = os.path.join(HERE, "batches")
sys.path.insert(0, HERE)
import verify

state = json.load(open(os.path.join(HERE, "state.json")))
TOTAL_FILES = state["total_files"]
TOTAL_BATCHES = state["total_batches"]


def sh(cmd, cwd):
    r = subprocess.run(cmd, shell=True, cwd=cwd, capture_output=True, text=True)
    return r.stdout.strip()


def batch_files(n):
    p = os.path.join(BATCHES, f"batch_{n:03d}.txt")
    return [l.split("\t")[0].strip() for l in open(p) if l.strip()] if os.path.exists(p) else []


L = []
w = L.append
w("# Branch progress log")
w("")
w("Running log of the automated clean-up of `leetcode_python/`, one section per branch.")
w("Generated by `script/py_multi_version/gen_progress.py` — **do not hand-edit**; every")
w("figure is read back from git or re-verified against the files on disk.")
w("")
w(f"_Snapshot: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}_")
w("")
w("## Where this work came from")
w("")
w("Audit of `leetcode_python/`: **2,868 files** holding **6,967** real solution")
w("implementations across 7,847 `# V<n>` markers. Three tasks fell out of it:")
w("")
w("| # | Task | Size found by audit | Status |")
w("|---|------|---------------------|--------|")
w("| 1 | Add missing `# time =` / `# space =` | 373 blocks in 142 files | not started |")
w("| 2 | Fix code format | 90 files with py2/tab defects; 366 duplicate blocks in 264 files; 375 files with no `V0`; ~9,300 whitespace fixes | not started |")
w(f"| 3 | Every LC needs >=3 solution versions | **{TOTAL_FILES:,}** files short (1,913 have 1, 258 have 2, 5 have none) | in progress |")
w("")
w("Task 2's dedup pass must run **after** task 3, or the two fight over the same version")
w("markers.")
w("")
w("A note on the count: a first pass put task 3 at 2,168 files, using a counter that")
w("treated a `pass`-only block as an implementation. `audit.py` does not, which is the")
w("stricter and correct reading, and it moves the figure to 2,176. The 8 extra files were")
w("appended as batches 346-347 rather than renumbering the work-list. Run")
w("`audit.py --report` for the live number — it always measures the tree.")
w("")

# ── per-branch ────────────────────────────────────────────────────────────────
grand_ok = 0
grand_dispatched = 0
branch_rows = []

for br, info in sorted(state["branches"].items(), key=lambda kv: kv[1]["wave"]):
    wt, base = info["worktree"], info["base"]
    # Diff against the commit the branch FORKED from, not the moving `master` ref —
    # once a wave is merged, `master..HEAD` is empty and the wave would read as undone.
    base_sha = info.get("base_sha", base)
    live = os.path.isdir(wt)
    verify.REPO = wt
    verify.WT = os.path.join(wt, "leetcode_python")
    verify.BASE = base_sha
    verify._added = None

    w(f"## `{br}`  (wave {info['wave']})")
    w("")
    w(f"**Task**: {info['task']}")
    w("")
    w(f"- Forked from `{base}` at `{base_sha}`  |  Worktree: `{wt}`"
      + ("" if live else "  _(worktree removed)_"))
    if live:
        w(f"- HEAD: `{sh('git log -1 --format=%h\\ %s', wt)}`")
        w(f"- Commits on branch: {sh(f'git rev-list --count {base_sha}..HEAD', wt) or 0}")
        w(f"- Pushed: `{sh('git rev-parse --abbrev-ref --symbolic-full-name @{u}', wt) or 'not pushed'}`")
    if info.get("merged"):
        w(f"- **Merged into `{base}`**")
    w("")

    committed = set()
    if live:
        committed = set(sh(f"git diff --name-only {base_sha}..HEAD -- leetcode_python", wt).split("\n")) - {""}

    rows = []; b_ok = b_files = 0; outstanding = []
    for n in info["dispatched"]:
        files = batch_files(n)
        if not files:
            continue
        okc = failc = 0
        for f in files:
            try:
                _, probs = verify.check(f) if live else (0, ["worktree gone"])
            except FileNotFoundError:
                probs = ["missing"]
            if probs:
                failc += 1
                if n in info["reported"]:
                    outstanding.append(f"`{f}` — {probs[0]}")
            else:
                okc += 1
        ncomm = sum(1 for f in files if f"leetcode_python/{f}" in committed)
        if n not in info["reported"]:
            st = "in flight"
        elif ncomm == len(files):
            st = "committed"
        elif failc == 0:
            st = "verified"
        else:
            st = "needs rework"
        rows.append((n, len(files), okc, failc, ncomm, st))
        b_ok += okc; b_files += len(files)

    w("| Batch | Files | Verified OK | Needs rework | Committed | Status |")
    w("|-------|-------|-------------|--------------|-----------|--------|")
    for r in rows:
        w(f"| {r[0]:03d} | {r[1]} | {r[2]} | {r[3]} | {r[4]} | {r[5]} |")
    w("")
    w(f"Wave total: **{b_ok}/{b_files}** files verified complete."
      + (" Batches still running are marked *in flight*; their counts are partial."
         if any(r[5] == "in flight" for r in rows) else ""))
    w("")
    if outstanding:
        w("Outstanding problems on batches that have reported:")
        w("")
        for o in outstanding:
            w(f"- {o}")
        w("")

    grand_ok += b_ok; grand_dispatched += b_files
    branch_rows.append((br, info["wave"], b_files, b_ok, len(committed)))

# ── rollup ───────────────────────────────────────────────────────────────────
w("## Task 3 rollup")
w("")
w("| Wave | Branch | Dispatched | Verified | Committed |")
w("|------|--------|------------|----------|-----------|")
for br, wave, nf, nok, ncomm in branch_rows:
    w(f"| {wave} | `{br}` | {nf} | {nok} | {ncomm} |")
w("")
pct = 100.0 * grand_ok / TOTAL_FILES
w(f"- In scope: **{TOTAL_FILES:,}** files across **{TOTAL_BATCHES}** batches")
w(f"- Dispatched so far: **{grand_dispatched}**")
w(f"- Verified complete: **{grand_ok}** ({pct:.1f}%)")
w(f"- Remaining: **{TOTAL_FILES - grand_ok:,}**")
w("")

w("## Definition of done")
w("")
w("Enforced mechanically by `script/py_multi_version/verify.py`; a file passes only if:")
w("")
w("- at least **3 blocks with real code** — a `pass`/bare-`return` placeholder does not")
w("  count toward the 3")
w("- every real block carries both `# time =` and `# space =` in its header")
w("- no two blocks are identical after comment/whitespace normalisation, which is what")
w("  stops this pass from re-creating the 366 duplicates task 2 has to remove")
w("- the file parses under `ast.parse`")
w("- **added** lines carry no tabs, no trailing whitespace and no py2 constructs, and the")
w("  file ends in exactly one newline. Pre-existing formatting debt is deliberately out")
w("  of scope here — it belongs to task 2")
w("")
w("Each new block also gets the house 4-line header (`# V0-N` / `# IDEA :` / `# time =` /")
w("`# space =`) with its own honest complexity, and every solution is run against the")
w("problem's docstring examples plus randomized cross-checks before it counts. Existing")
w("blocks are left byte-for-byte unchanged — the pass is additive.")
w("")
w("`verify.py` audits its own checkout by default; set `PMV_WORKTREE` to point it at")
w("another branch's worktree, which is how this doc reports on every wave at once.")
w("")

open(os.path.join(REPO, "doc", "branch-progress.md"), "w").write("\n".join(L) + "\n")
print("wrote doc/branch-progress.md")
