"""

2607. Make K-Subarray Sums Equal
Medium

You are given a 0-indexed integer array arr and an integer k. The array arr is circular. In other words, the first element of the array is the next element of the last element, and the last element of the array is the previous element of the first element.

You can do the following operation any number of times:

- Pick any element from arr and increase or decrease it by 1.

Return the minimum number of operations such that the sum of each subarray of length k is equal.

A subarray is a contiguous part of the array.


Example 1:

Input: arr = [1,4,1,3], k = 2
Output: 1
Explanation: we can do one operation on index 1 to make its value equal to 3.
The array after the operation is [1,3,1,3]
- Subarray starts at index 0 is [1, 3], and its sum is 4
- Subarray starts at index 1 is [3, 1], and its sum is 4
- Subarray starts at index 2 is [1, 3], and its sum is 4
- Subarray starts at index 3 is [3, 1], and its sum is 4

Example 2:

Input: arr = [2,5,5,7], k = 3
Output: 5
Explanation: we can do three operations on index 0 to make its value equal to 5 and two operations on index 3 to make its value equal to 5.
The array after the operations is [5,5,5,5]
- Subarray starts at index 0 is [5,5,5], and its sum is 15
- Subarray starts at index 1 is [5,5,5], and its sum is 15
- Subarray starts at index 2 is [5,5,5], and its sum is 15
- Subarray starts at index 3 is [5,5,5], and its sum is 15


Constraints:

1 <= k <= arr.length <= 10^5
1 <= arr[i] <= 10^9

"""

# V0
# IDEA : GCD CYCLE GROUPING + MEDIAN
#
#   two neighbouring windows of length k differ by one element in / one out:
#     sum(i) == sum(i+1)  <=>  arr[i] == arr[(i + k) % n]
#
#   so following the chain i -> i+k -> i+2k ... (mod n) forces a whole group
#   of indices to hold the SAME value. that chain visits exactly the indices
#   congruent to i modulo g, where g = gcd(n, k) — a classic result about the
#   cyclic subgroup generated by k in Z_n. so there are g independent groups:
#       group r = arr[r], arr[r+g], arr[r+2g], ...
#
#   inside a group every element must become one common value, and the cost
#   sum|x - v| is minimised at the MEDIAN of the group (any median works when
#   the group size is even).
#
#   NOTE : the +/-1 operations are unbounded and independent, so the groups
#          never interact — just add up their costs.
#   NOTE : n up to 1e5 and values up to 1e9, so the total can exceed 32 bits
#          (Python ints handle this for free).
#
# time = O(n log n), space = O(n)
class Solution(object):
    def makeSubKSumEqual(self, arr, k):
        def gcd(a, b):
            while b:
                a, b = b, a % b
            return a

        n = len(arr)
        g = gcd(n, k)
        res = 0
        for r in range(g):
            group = sorted(arr[r:n:g])
            mid = group[len(group) // 2]
            for x in group:
                res += abs(x - mid)
        return res
